---
title: "Lab4-Logistic Regression, LDA, QDA, KNN"
output: html_document
---

# install library
```{r}
install.packages('ISLR')
install.packages('MASS')
```

# load library
```{r}
library(ISLR)
library(MASS)
library(class)
```

# Smarket dataset data exploration
```{r}
names(Smarket)
dim(Smarket)
summary(Smarket)
pairs(Smarket)
cor(Smarket[,-9])
attach(Smarket)
plot(Volume)
```

# 1. logistic regression
```{r}
glm.fit = glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume, data=Smarket, family=binomial)
summary(glm.fit)
coef(glm.fit)
summary(glm.fit)$coef
glm.probs = predict(glm.fit, type="response")
glm.probs
# show dummy variable
contrasts(Direction)
# create a vector of 1250 Down elements
glm.pred = rep("Down", 1250)
# transforms elements with over 0.5 probability to Up
glm.pred[glm.probs > .5]="Up"
# create confusion matrix
table(glm.pred, Direction)
mean(glm.pred == Direction)
```

# create held-out data to obtain test error rate 
```{r}
train = (Year < 2005)
Smarket.2005 = Smarket[!train,]
dim(Smarket.2005)
Direction.2005 = Direction[!train]
glm.fit2 = glm(Direction~Lag1+Lag2+Lag3+Lag4+Lag5+Volume, data=Smarket, family=binomial, subset=train)
glm.probs2 = predict(glm.fit2, Smarket.2005, type="response")
glm.pred2 = rep("Down", 252)
glm.pred2[glm.probs2 > .5] = "Up"
table(glm.pred2, Direction.2005)
mean(glm.pred2 == Direction.2005)
mean(glm.pred2 != Direction.2005)
```

# remove parameters with large p-values
```{r}
glm.fit3 = glm(Direction ~ Lag1 + Lag2, data=Smarket, family=binomial, subset=train)
glm.probs3 = predict(glm.fit3, Smarket.2005, type="response")
glm.pred3=rep("Down", 252)
glm.pred3[glm.probs3 > .5] = "Up"
table(glm.pred3, Direction.2005)
mean(glm.pred3 == Direction.2005)
```

# 2.LDA

```{r}
lda.fit = lda(Direction ~ Lag1+Lag2, data=Smarket, subset=train)
lda.fit
lda.pred = predict(lda.fit, Smarket.2005)
names(lda.pred)
lda.class = lda.pred$class
table(lda.class, Direction.2005)
mean(lda.class == Direction.2005)
sum(lda.pred$posterior[,1] >= .5)
sum(lda.pred$posterior[,1] < .5)
```

# 3. QDA
```{r}
qda.fit = qda(Direction ~ Lag1+Lag2, data=Smarket, subset=train)
qda.fit
qda.class = predict(qda.fit, Smarket.2005)$class
table(qda.class, Direction.2005)
mean(qda.class == Direction.2005)
```

# 4. KNN
```{r}
train.X = cbind(Lag1, Lag2)[train,]
test.X = cbind(Lag1, Lag2)[!train,]
train.Direction = Direction[train]
set.seed(1)
knn.pred = knn(train.X, test.X, train.Direction, k=1)
table(knn.pred, Direction.2005)
mean(knn.pred == Direction.2005)
knn.pred3 = knn(train.X, test.X, train.Direction, k=3)
table(knn.pred3, Direction.2005)
mean(knn.pred3 == Direction.2005)
```