---
title: "Lab 8-Decision Trees"
output: html_document
---

# install packages
```{r}
install.packages("tree")
install.packages("ISLR")
install.packages("randomForest")
install.packages("gbm")
```

```{r}
library(tree)
library(ISLR)
library(MASS)
library(randomForest)
library(gbm)
```

# Fitting Classification Trees
```{r}
attach(Carseats)
# recode Sales as a binary variable
High = ifelse(Sales<=8, "No", "Yes")
# merge High with the data
Carseats = data.frame(Carseats, High)

# fit a classification tree to predict High using all variables but Sales
tree.carseats = tree(High ~.-Sales, Carseats)
tree.carseats

plot(tree.carseats)

# split train and test set
set.seed(2)
train = sample(1:nrow(Carseats), 200)
Carseats.test = Carseats[-train,]
High.test = High[-train]
tree.carseats = tree(High~.-Sales, Carseats, subset=train)
tree.pred = predict(tree.carseats, Carseats.test, type="class")
table(tree.pred, High.test)

# pruning tree?
set.seed(3)
cv.carseats = cv.tree(tree.carseats, FUN=prune.misclass)
names(cv.carseats)
par(mfrow=c(1,2))
plot(cv.carseats$size, cv.carseats$dev, type="b")
plot(cv.carseats$k, cv.carseats$dev, type="b")
prune.carseats = prune.misclass(tree.carseats, best=9)
plot(prune.carseats)
text(prune.carseats, pretty=0)
tree.pred = predict(prune.carseats, Carseats.test, type="class")
table(tree.pred, High.test)
```


# Fitting Regression Trees
```{r}
# fit a regression tree
set.seed(1)
train = sample(1:nrow(Boston), nrow(Boston)/2)
tree.boston = tree(medv ~ ., Boston, subset=train)
summary(tree.boston)
plot(tree.boston)
text(tree.boston, pretty=0)

# prune the tree?
cv.boston = cv.tree(tree.boston)
plot(cv.boston$size, cv.boston$dev, type="b")

prune.boston = prune.tree(tree.boston, best=5)
plot(prune.boston)
text(prune.boston, pretty=0)

# make predictions
yhat = predict(tree.boston, newdata=Boston[-train,])
boston.test = Boston[-train, "medv"]
plot(yhat, boston.test)
abline(0,1)
mean((yhat - boston.test)^2)
```


# Bagging and Random Forests
```{r}
# bagging
set.seed(1)
bag.boston = randomForest(medv ~ ., data=Boston, subset=train, mtry=13, importance=TRUE)
bag.boston
yhat.bag = predict(bag.boston, newdata=Boston[-train,])
plot(yhat.bag, boston.test)
abline(0,1)
mean((yhat.bag-boston.test)^2)

# random forest
set.seed(1)
rf.boston = randomForest(medv ~ ., data=Boston, subset=train, mtry=6, importance=TRUE)
yhat.rf = predict(rf.boston, newdata=Boston[-train,])
mean((yhat.rf-boston.test)^2)
importance(rf.boston)
varImpPlot(rf.boston)
```


# Boosting
```{r}
set.seed(1)
boost.boston = gbm(medv ~ ., data=Boston[train,], distribution="gaussian", n.trees=5000, interaction.depth=4)
summary(boost.boston)
par(mfrow=c(1,2))
plot(boost.boston,i="rm")
plot(boost.boston,i="lstat")
yhat.boost=predict(boost.boston, newdata=Boston[-train,], n.trees=5000)
mean((yhat.boost-boston.test)^2)
```

